version: '3'

services:
  mysql:
    image: mysql
    volumes:
      - mysql-data:/var/lib/mysql
    container_name: "aac-mysql"
    env_file: ./aac/mysql.env
    restart: always
  aac:
    image: simpatico-project/aac
    depends_on: 
      - mysql
    links:
      - mysql:mysql-server
    container_name: "aac"
    ports:
      - 8000:8080
    env_file: ./aac/aac.env
  mongo:
   image: mongo:3.6.2-jessie
   container_name: gamification-mongo
   ports:
     - "50000:27017"
   volumes:
     - mongo-data:/data/db
  gamification-engine:
    image: simpaticoproject/gamificationengine:2.4.0-53f06cd
    container_name: gamification-engine
    ports:
      - "8010:8010"
      - "7777:7777"
    depends_on:
      - mongo
    links:
      - mongo:mongodb
    volumes:
      - ./gamification/run-configs:/app/run-configs
volumes:
  mysql-data:
  mongo-data:
