version: '3'

services:
  aac-db:
    image: mysql
    volumes:
      - aac-db-data:/var/lib/mysql
    container_name: aac-mysql
    env_file: ./aac/mysql.env
    restart: always
  aac:
    image: simpatico-project/aac
    depends_on: 
      - aac-db
    links:
      - aac-db:mysql-server
    container_name: aac
    ports:
      - 8000:8080
    env_file: ./aac/aac.env
  gamification-db:
   image: mongo:3.6.2-jessie
   container_name: gamification-db
   ports:
     - 50000:27017
   volumes:
     - gamification-db-data:/data/db
  gamification-engine:
    image: simpaticoproject/gamificationengine:2.4.0-53f06cd
    container_name: gamification-engine
    ports:
      - 8010:8010
      - 7777:7777
    depends_on:
      - gamification-db
    links:
      - gamification-db:mongodb
    volumes:
      - ./gamification/run-configs:/app/run-configs
  upm-db:
    image: upm-db
    volumes:
      - upm-db-data:/var/lib/mysql
    container_name: upm-db
    env_file: ./upm/upm-db.env
    restart: always
  upm-server:
    image: upm-server
    depends_on: 
      - upm-db
    links:
      - upm-db:mysql-server
    container_name: upm-server
    ports:
      - 1616:1616
      - 1717:1717
  sae-db:
    image: mongo:3.6.2-jessie
    container_name: sae-db
    ports:
      - 50001:27017
    volumes:
      - sae-db-data:/data/db
  sae-server:
    image: simpaticoproject/adaptationengines:1.1.0
    container_name: sae-server
    ports:
      - 8001:80
    depends_on:
      - sae-db
    links:
      - sae-db:mongodb
    env_file: ./sae/app.env
  esm:
    build:
      context: ../eSM
    container_name: esm
    volumes:
      - ./esm:/app-run
    entrypoint:
      - sh
      - /app-run/docker-entrypoint.sh
    ports:
      - 3700:3700
  qae-gateway:
    image: nginx:alpine
    volumes:
      - ./citizenpedia/web:/usr/share/nginx/html
      - ./citizenpedia/web/conf.d:/etc/nginx/conf.d
    ports:
      - 8100:80
    restart: always
  qae-db:
    restart: always
    image: mongo:latest
    container_name: qae-db
    volumes:
      - qae-db-data:/data/db
    ports:
      - 50002:27017
  qae:
    build:
      context: ../citizenpedia
    depends_on:
      - qae-db
    links:
      - qae-db:mongodb
    volumes:
      - ./citizenpedia/server:/app-run
    entrypoint:
      - sh
      - /app-run/docker-entrypoint.sh
    ports:
      - 9000:9000
volumes:
  aac-db-data:
  gamification-db-data:
  upm-db-data:
  sae-db-data:
  qae-db-data:
